export enum DocumentStatus {
  CARGADO = 'CARGADO',
  PROCESANDO = 'PROCESANDO',
  PROCESADO = 'PROCESADO',
  PENDIENTE_REVISION = 'PENDIENTE_REVISION',
  CONFIRMADO = 'CONFIRMADO',
  ERROR_OCR = 'ERROR_OCR',
}