const test = require('node:test');
const assert = require('node:assert/strict');
const { DocumentComplianceService } = require('../dist/src/modules/ocr/document-compliance.service');
const { OcrService } = require('../dist/src/modules/ocr/ocr.service');
const { validateDirectDocumentAssociation } = require('../dist/src/modules/expense-requests/expense-requests.service');

function fiscalHarness({ type = 'FACTURA', taxId = '9876543-2', receiverTaxId = '9876543-2', receiverName = 'EMPRESA XYZ, S.A.', confidence = 99.4, text = '', policy = null, used = false, requestCompany = null, companies, manuallyCorrected = false } = {}) {
  let current; const audits = [];
  const fields = [];
  if (receiverTaxId !== null) fields.push({ fieldName: 'buyer_nit', detectedValue: manuallyCorrected ? 'OCR-INCORRECTO' : receiverTaxId, finalValue: receiverTaxId, confidence, wasCorrected: manuallyCorrected });
  if (receiverName !== null) fields.push({ fieldName: 'buyer_name', detectedValue: receiverName, finalValue: receiverName, confidence });
  const masterCompanies = companies === undefined ? [{ id: 'company', taxId, name: 'EMPRESA XYZ', legalName: 'EMPRESA XYZ, S.A.', tradeName: null, active: true, countryId: 'country', currencyId: 'currency', country: {} }] : companies;
  const document = { id: 'doc', user: { id: 'user', role: 'SOLICITANTE', company: { id: 'uploader-company', taxId: '1111111', countryId: 'other-country' } }, expenseRequest: requestCompany ? { id: 'request', companyId: requestCompany.id, company: requestCompany } : null, ocrResult: { id: 'ocr', processStatus: 'PENDIENTE_REVISION', documentTypeDetected: type, extractedText: text, extractedFields: fields, currencyCode: 'GTQ', totalAmount: 100, finalVoucherType: null, detectedVoucherType: null, usedInSettlement: used } };
  const tx = { oCRResult: { update: async ({ data }) => { current = data; } }, oCRComplianceDecision: { create: async ({ data }) => { audits.push(data); return { id: `audit-${audits.length}`, ...data }; } } };
  const prisma = { document: { findUnique: async () => document }, company: { findMany: async () => masterCompanies }, $transaction: async callback => callback(tx) };
  const policyEngine = { evaluate: async () => ({ results: policy ? [{ ruleId: 'rule', code: 'ALLOW_DOC', name: 'Permitir documento', field: 'DOCUMENT_TYPE', status: 'OK', message: 'Permitido', priority: 1 }] : [] }) };
  const config = { get: () => 80 };
  return { service: new DocumentComplianceService(prisma, policyEngine, config), current: () => current, audits };
}

test('caso 1 factura con NIT correcto queda aprobada', async () => { const h=fiscalHarness(); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'VALIDACION_FISCAL_APROBADA'); });
test('caso 2 factura CF queda rechazada', async () => { const h=fiscalHarness({receiverTaxId:'CF',receiverName:'CONSUMIDOR FINAL'}); await h.service.evaluate('doc'); assert.equal(h.current().complianceReason,'FACTURA_CONSUMIDOR_FINAL'); });
test('caso 3 asociación histórica a solicitud no altera empresa detectada por OCR', async () => { const requestCompany={id:'company',taxId:'9876543-2',countryId:'country',currencyId:'currency',country:{}}; const h=fiscalHarness({receiverTaxId:'5555555-5',requestCompany,companies:[{id:'other',taxId:'5555555-5',name:'OTRA EMPRESA',legalName:'OTRA EMPRESA',countryId:'country',currencyId:'currency',country:{}}]}); await h.service.evaluate('doc'); assert.equal(h.current().fiscalCompanyId,'other'); assert.equal(h.current().complianceResult,'VALIDACION_FISCAL_APROBADA'); });
test('caso 4 NIT no identificado queda pendiente', async () => { const h=fiscalHarness({receiverTaxId:null}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'VALIDACION_FISCAL_PENDIENTE_REVISION'); });
test('caso 5 NIT correcto con baja confianza queda pendiente', async () => { const h=fiscalHarness({confidence:79.99}); await h.service.evaluate('doc'); assert.equal(h.current().complianceReason,'CONFIANZA_NIT_INSUFICIENTE'); });
test('caso 6 recibo con política queda permitido y registra política', async () => { const h=fiscalHarness({type:'RECIBO',policy:true}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'DOCUMENTO_PERMITIDO_POR_POLITICA'); assert.equal(h.audits[0].appliedPolicyCode,'ALLOW_DOC'); });
test('caso 7 recibo sin política queda rechazado', async () => { const h=fiscalHarness({type:'RECIBO'}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'DOCUMENTO_NO_PERMITIDO'); });
test('caso 8 otro tipo con política queda permitido', async () => { const h=fiscalHarness({type:'OTRO',policy:true}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'DOCUMENTO_PERMITIDO_POR_POLITICA'); });
test('caso 9 otro tipo sin política queda rechazado', async () => { const h=fiscalHarness({type:'OTRO'}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'DOCUMENTO_NO_PERMITIDO'); });
test('caso 10 corrección manual de tipo conserva historial inmutable', async () => { let correction; const field={id:'field',fieldName:'document_type',detectedValue:'FACTURA',normalizedValue:'FACTURA',finalValue:'FACTURA',confidence:99}; const tx={extractedField:{findFirst:async()=>field,update:async()=>{}},oCRFieldCorrection:{create:async({data})=>{correction=data;}},oCRResult:{update:async()=>{}}}; const prisma={document:{findUnique:async()=>({id:'doc',userId:'user',status:'PENDIENTE_REVISION',ocrResult:{id:'ocr'}})},$transaction:async cb=>cb(tx)}; const compliance={evaluate:async()=>{}}; const service=new OcrService(prisma,{}, {}, compliance); await service.updateFields('doc',{fields:[{id:'field',fieldValue:'RECIBO',reason:'Clasificación incorrecta'}]},{id:'user',role:'ADMIN'}); assert.equal(correction.ocrValue,'FACTURA'); assert.equal(correction.finalValue,'RECIBO'); assert.equal(correction.userId,'user'); assert.equal(correction.reason,'Clasificación incorrecta'); });
test('caso 11 comprobante rechazado no es elegible', async () => { const h=fiscalHarness({type:'RECIBO'}); await h.service.evaluate('doc',null,true); assert.equal(h.current().eligibleForSettlement,false); });
test('caso 12 comprobante permitido y revisado queda elegible', async () => { const h=fiscalHarness({type:'RECIBO',policy:true}); await h.service.evaluate('doc',null,true); assert.equal(h.current().eligibleForSettlement,true); });
test('caso 13 documento sin solicitud identifica empresa exclusivamente por NIT receptor', async () => { const h=fiscalHarness(); await h.service.evaluate('doc'); assert.equal(h.current().fiscalCompanyId,'company'); assert.equal(h.current().fiscalCompanyIdentificationStatus,'EMPRESA_IDENTIFICADA'); assert.notEqual(h.current().fiscalCompanyId,'uploader-company'); });
test('caso 14 NIT inexistente queda como empresa no identificada', async () => { const h=fiscalHarness({companies:[]}); await h.service.evaluate('doc'); assert.equal(h.current().complianceReason,'NIT_RECEPTOR_NO_REGISTRADO_MAESTRO'); assert.equal(h.current().fiscalCompanyIdentificationStatus,'EMPRESA_NO_IDENTIFICADA'); assert.equal(h.current().fiscalCompanyId,null); });
test('caso 15 diferencias menores de razón social no rechazan NIT coincidente', async () => { const h=fiscalHarness({receiverName:'EMPRESA XYZ'}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'VALIDACION_FISCAL_APROBADA'); assert.equal(h.current().fiscalCompanyWarning,null); });
test('caso 16 nunca utiliza la empresa del usuario autenticado', async () => { const h=fiscalHarness({companies:[]}); await h.service.evaluate('doc'); assert.equal(h.audits[0].companyId,null); assert.equal(h.audits[0].expectedTaxId,null); });
test('caso 17 corrección manual del NIT reidentifica empresa sin ejecutar OCR', async () => { const h=fiscalHarness({manuallyCorrected:true}); await h.service.evaluate('doc'); assert.equal(h.current().fiscalCompanyId,'company'); assert.equal(h.current().fiscalCompanyIdentificationMethod,'CORRECCION_MANUAL'); });
test('caso 18 documento OCR no se asocia directamente a solicitud', () => assert.throws(() => validateDirectDocumentAssociation([{fileName:'factura.pdf',ocrResult:{finalVoucherType:'FACTURA',fiscalCompanyId:'company'}}]), /debe incorporarse desde la liquidación/));
test('caso 19 documento técnico conserva asociación directa compatible', () => assert.doesNotThrow(() => validateDirectDocumentAssociation([{fileName:'desembolso.pdf',ocrResult:null}])));
test('caso 20 razón social materialmente distinta genera advertencia, no rechazo', async () => { const h=fiscalHarness({receiverName:'NOMBRE OCR DIFERENTE'}); await h.service.evaluate('doc'); assert.equal(h.current().complianceResult,'VALIDACION_FISCAL_APROBADA'); assert.equal(h.current().fiscalCompanyWarning,'RAZON_SOCIAL_RECEPTOR_DIFIERE'); });
