import { Badge, Box, Button, Flex, Heading, Input, SimpleGrid, Spinner, Stack, Table, Text, Textarea } from '@chakra-ui/react';
import { useEffect, useState } from 'react';
import { functionalTestsApi, FunctionalRecord } from './functional-tests.service';
export function FunctionalTestsPage(){
 const [rows,setRows]=useState<FunctionalRecord[]>([]); const [selected,setSelected]=useState<FunctionalRecord|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
 const [project,setProject]=useState(''); const [analyst,setAnalyst]=useState(''); const [performed,setPerformed]=useState('');
 const [caseForm,setCaseForm]=useState({requirementCode:'REQ-001',requirementName:'',testDescription:'',acceptanceCriteria:'',estimatedTime:''});
 const load=async()=>{setLoading(true);try{setRows(await functionalTestsApi.list())}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
 const create=async()=>{setMessage('');const r=await functionalTestsApi.create({project,analystName:analyst,performedByName:performed,startedAt:new Date().toISOString()});setProject('');setAnalyst('');setPerformed('');await load();setSelected(await functionalTestsApi.get(r.id));setMessage('Registro creado.');};
 const addCase=async()=>{if(!selected)return;await functionalTestsApi.addCase(selected.id,caseForm);setSelected(await functionalTestsApi.get(selected.id));await load();setCaseForm({...caseForm,testDescription:'',acceptanceCriteria:''});};
 const execute=async(id:string,result:'EXITOSA'|'NO_EXITOSA')=>{await functionalTestsApi.execute(id,{result,observedResult:result==='EXITOSA'?'Resultado conforme':'Resultado no conforme',...(result==='NO_EXITOSA'?{observations:'Se requiere corrección'}:{})});if(selected)setSelected(await functionalTestsApi.get(selected.id));await load();};
 return <Box p={6}><Flex justify="space-between" mb={6}><Box><Heading size="lg">Pruebas de requerimientos funcionales</Heading><Text color="gray.600">Registro persistente y trazable de ejecución y evidencia.</Text></Box></Flex>
 <Stack gap={3} mb={8} borderWidth="1px" borderRadius="md" p={4}><Heading size="sm">Nuevo registro</Heading><SimpleGrid columns={{base:1,md:3}} gap={3}><Input placeholder="Proyecto" value={project} onChange={e=>setProject(e.target.value)}/><Input placeholder="Analista encargado" value={analyst} onChange={e=>setAnalyst(e.target.value)}/><Input placeholder="Pruebas realizadas por" value={performed} onChange={e=>setPerformed(e.target.value)}/></SimpleGrid><Button alignSelf="start" colorPalette="blue" onClick={create} disabled={!project||!analyst||!performed}>Crear registro</Button></Stack>
 {message&&<Text color="green.600" mb={3}>{message}</Text>}{loading?<Spinner/>:<Table.Root variant="outline"><Table.Header><Table.Row><Table.ColumnHeader>Proyecto</Table.ColumnHeader><Table.ColumnHeader>Estado</Table.ColumnHeader><Table.ColumnHeader>Total</Table.ColumnHeader><Table.ColumnHeader>Realizadas</Table.ColumnHeader><Table.ColumnHeader>Exitosas</Table.ColumnHeader><Table.ColumnHeader>% realizadas</Table.ColumnHeader><Table.ColumnHeader>Acción</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{rows.map(r=><Table.Row key={r.id}><Table.Cell>{r.project}</Table.Cell><Table.Cell><Badge>{r.status}</Badge></Table.Cell><Table.Cell>{r.total}</Table.Cell><Table.Cell>{r.performed}</Table.Cell><Table.Cell>{r.successful}</Table.Cell><Table.Cell>{r.performedPercentage}%</Table.Cell><Table.Cell><Button size="sm" onClick={async()=>setSelected(await functionalTestsApi.get(r.id))}>Ver detalle</Button></Table.Cell></Table.Row>)}</Table.Body></Table.Root>}
 {selected&&<Box mt={8} borderWidth="1px" borderRadius="md" p={4}><Flex justify="space-between"><Heading size="md">{selected.project}</Heading><Button size="sm" onClick={()=>setSelected(null)}>Cerrar</Button></Flex><SimpleGrid columns={{base:2,md:5}} gap={3} my={4}>{[['Total',selected.total],['Realizadas',selected.performed],['Pendientes',selected.pending],['Exitosas',selected.successful],['% exitosas',`${selected.successfulPercentage}%`]].map(([k,v])=><Box key={String(k)} bg="gray.50" p={3}><Text fontSize="sm">{k}</Text><Text fontWeight="bold">{v}</Text></Box>)}</SimpleGrid><Stack gap={3} mb={5}><Heading size="sm">Agregar caso</Heading><SimpleGrid columns={{base:1,md:2}} gap={2}><Input placeholder="Código requerimiento" value={caseForm.requirementCode} onChange={e=>setCaseForm({...caseForm,requirementCode:e.target.value})}/><Input placeholder="Nombre requerimiento" value={caseForm.requirementName} onChange={e=>setCaseForm({...caseForm,requirementName:e.target.value})}/><Input placeholder="Prueba a realizar" value={caseForm.testDescription} onChange={e=>setCaseForm({...caseForm,testDescription:e.target.value})}/><Textarea placeholder="Criterio de aceptación" value={caseForm.acceptanceCriteria} onChange={e=>setCaseForm({...caseForm,acceptanceCriteria:e.target.value})}/><Input placeholder="Tiempo estimado" value={caseForm.estimatedTime} onChange={e=>setCaseForm({...caseForm,estimatedTime:e.target.value})}/></SimpleGrid><Button alignSelf="start" onClick={addCase} disabled={!caseForm.requirementName||!caseForm.testDescription||!caseForm.acceptanceCriteria}>Agregar caso</Button></Stack><Table.Root variant="outline"><Table.Header><Table.Row><Table.ColumnHeader>Requerimiento</Table.ColumnHeader><Table.ColumnHeader>Prueba</Table.ColumnHeader><Table.ColumnHeader>Criterio</Table.ColumnHeader><Table.ColumnHeader>Estado</Table.ColumnHeader><Table.ColumnHeader>Resultado</Table.ColumnHeader><Table.ColumnHeader>Acción</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{selected.cases.map(c=><Table.Row key={c.id}><Table.Cell>{c.requirement.code} — {c.requirement.name}</Table.Cell><Table.Cell>{c.testDescription}</Table.Cell><Table.Cell>{c.acceptanceCriteria}</Table.Cell><Table.Cell>{c.status}</Table.Cell><Table.Cell>{c.result||'Pendiente'}</Table.Cell><Table.Cell>{c.status==='PENDIENTE'&&<Flex gap={2}><Button size="xs" colorPalette="green" onClick={()=>execute(c.id,'EXITOSA')}>Exitosa</Button><Button size="xs" colorPalette="red" onClick={()=>execute(c.id,'NO_EXITOSA')}>No exitosa</Button></Flex>}</Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box>}
 </Box>
}
