import { useMemo, useState } from 'react';
import { useQueries, useQuery } from '@tanstack/react-query';
import { Badge, Box, Button, Flex, Grid, Heading, Input, Spinner, Table, Text, VStack } from '@chakra-ui/react';
import { BarChart3, CheckCircle2, Clock3, FileWarning, RefreshCw, WalletCards } from 'lucide-react';
import { dashboardService, type DashboardFilters } from '../../services/dashboard.service';

const money=(value:number)=>new Intl.NumberFormat('es-GT',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(value||0);
const minutes=(value:number)=>value>=1440?`${(value/1440).toFixed(1)} dÃ­as`:value>=60?`${(value/60).toFixed(1)} h`:`${value||0} min`;
export function ExecutiveDashboardPage(){
 const [draft,setDraft]=useState<DashboardFilters>({}); const [filters,setFilters]=useState<DashboardFilters>({});
 const catalogs=useQuery({queryKey:['dashboard-filters'],queryFn:dashboardService.filters});
 const queries=useQueries({queries:[['summary',dashboardService.summary],['budget',dashboardService.budget],['workflow',dashboardService.workflow],['policies',dashboardService.policies],['approvals',dashboardService.approvals],['charts',dashboardService.charts],['trends',dashboardService.trends]].map(([key,fn]:any)=>({queryKey:['dashboard',key,filters],queryFn:()=>fn(filters)}))});
 const [summary,budget,workflow,policies,approvals,charts,trends]=queries.map(q=>q.data); const loading=queries.some(q=>q.isLoading); const error=queries.find(q=>q.error)?.error;
 return <VStack align="stretch" gap="5"><Flex justify="space-between" align={{base:'start',md:'center'}} direction={{base:'column',md:'row'}}><Box><Badge colorPalette="blue">InformaciÃ³n en tiempo real</Badge><Heading mt="2" size="lg">Dashboard Ejecutivo</Heading><Text color="gray.500">Indicadores consolidados para Gerencia, Finanzas y AdministraciÃ³n.</Text></Box><Button variant="outline" onClick={()=>queries.forEach(q=>q.refetch())}><RefreshCw size={16}/>Actualizar</Button></Flex>
 <Filters value={draft} catalogs={catalogs.data} onChange={setDraft} onApply={()=>setFilters({...draft})} onClear={()=>{setDraft({});setFilters({});}}/>
 {loading&&<Flex justify="center" py="12"><Spinner size="xl"/></Flex>}{error&&<Box bg="red.50" color="red.700" p="4" rounded="xl">No fue posible cargar los indicadores ejecutivos.</Box>}
 {!loading&&!error&&<><Grid templateColumns={{base:'1fr',sm:'repeat(2,1fr)',xl:'repeat(4,1fr)'}} gap="4"><Kpi title="Solicitudes" value={summary?.total} detail={`${summary?.pending||0} pendientes`} icon={BarChart3}/><Kpi title="Presupuesto disponible" value={money(budget?.available)} detail={`${budget?.consumptionPercentage||0}% consumido`} icon={WalletCards}/><Kpi title="Pendientes workflow" value={workflow?.pendingRequests} detail={`${workflow?.overdueRequests||0} atrasadas`} icon={Clock3}/><Kpi title="PolÃ­ticas evaluadas" value={policies?.evaluated} detail={`${policies?.violations||0} incumplimientos`} icon={FileWarning}/></Grid>
 <Grid templateColumns={{base:'1fr',xl:'1.35fr 1fr'}} gap="5"><Panel title="Estados de solicitudes"><BarList rows={[['Borradores',summary?.drafts],['Pendientes',summary?.pending],['Aprobadas',summary?.approved],['Rechazadas',summary?.rejected],['Observadas',summary?.observed],['Canceladas',summary?.cancelled]]}/></Panel><Panel title="Disponibilidad presupuestaria"><Grid templateColumns="1fr 1fr" gap="3"><Mini label="Aprobado" value={money(budget?.approved)}/><Mini label="Reservado" value={money(budget?.reserved)}/><Mini label="Ejecutado" value={money(budget?.executed)}/><Mini label="Disponible" value={money(budget?.available)}/></Grid><Donut value={budget?.consumptionPercentage||0}/></Panel></Grid>
 <Grid templateColumns={{base:'1fr',xl:'repeat(3,1fr)'}} gap="5"><Panel title="SLA"><Traffic label="Verde" value={workflow?.sla?.green} color="green.500"/><Traffic label="Amarillo" value={workflow?.sla?.yellow} color="yellow.400"/><Traffic label="Rojo" value={workflow?.sla?.red} color="red.500"/><Text mt="3" fontSize="sm">Tiempo promedio de aprobaciÃ³n: <b>{minutes(workflow?.averageApprovalMinutes)}</b></Text></Panel><Panel title="Resultados de polÃ­ticas"><BarList rows={[['Advertencias',policies?.warnings],['Incumplimientos',policies?.violations],['Requieren aprobaciÃ³n',policies?.approvalRequired],['Cumplen',policies?.ok]]}/></Panel><Panel title="Tendencia mensual"><LineChart rows={trends?.monthly||[]}/></Panel></Grid>
 <Grid templateColumns={{base:'1fr',xl:'1fr 1fr'}} gap="5"><Panel title="Aprobadores"><DataTable rows={approvals||[]} columns={[['name','Usuario'],['pending','Pendientes'],['approved','Aprobadas'],['averageMinutes','Promedio (min)']]}/></Panel><Panel title="Consumo por empresa"><DataTable rows={charts?.companies||[]} columns={[['label','Empresa'],['requests','Solicitudes'],['reserved','Reservado'],['executed','Ejecutado']]}/></Panel></Grid>
 <Grid templateColumns={{base:'1fr',xl:'repeat(2,1fr)'}} gap="5"><Panel title="Consumo por paÃ­s"><DataTable rows={charts?.countries||[]} columns={[['label','PaÃ­s'],['requests','Solicitudes'],['reserved','Reservado'],['executed','Ejecutado']]}/></Panel><Panel title="Top 10 tipos de gasto"><BarList rows={(charts?.expenseTypes||[]).map((x:any)=>[x.label,x.amount])} moneyValues/></Panel><Panel title="Top 10 centros de costo"><BarList rows={(charts?.costCenters||[]).map((x:any)=>[x.label,x.amount])} moneyValues/></Panel><Panel title="Top 10 cuentas presupuestarias"><BarList rows={(charts?.budgetAccounts||[]).map((x:any)=>[x.label,x.amount])} moneyValues/></Panel></Grid></>}
 </VStack>;
}
function Filters({value,catalogs,onChange,onApply,onClear}:any){const field=(key:string,val:string)=>onChange({...value,[key]:val||undefined});return <Box bg="white" borderWidth="1px" rounded="2xl" p="4"><Grid templateColumns={{base:'1fr',md:'repeat(3,1fr)',xl:'repeat(5,1fr)'}} gap="3"><Select value={value.companyId} onChange={(v:string)=>field('companyId',v)} options={catalogs?.companies}/><Select value={value.countryId} onChange={(v:string)=>field('countryId',v)} options={catalogs?.countries}/><Select value={value.status} onChange={(v:string)=>field('status',v)} options={(catalogs?.statuses||[]).map((x:string)=>({id:x,name:x}))}/><Select value={value.priority} onChange={(v:string)=>field('priority',v)} options={(catalogs?.priorities||[]).map((x:string)=>({id:x,name:x}))}/><Select value={value.type} onChange={(v:string)=>field('type',v)} options={(catalogs?.expenseTypes||[]).map((x:string)=>({id:x,name:x}))}/><Select value={value.requesterId} onChange={(v:string)=>field('requesterId',v)} options={catalogs?.users}/><Input type="date" value={value.dateFrom||''} onChange={e=>field('dateFrom',e.target.value)}/><Input type="date" value={value.dateTo||''} onChange={e=>field('dateTo',e.target.value)}/><Input placeholder="Centro de costo" value={value.costCenter||''} onChange={e=>field('costCenter',e.target.value)}/><Flex gap="2"><Button flex="1" colorPalette="blue" onClick={onApply}>Aplicar</Button><Button variant="outline" onClick={onClear}>Limpiar</Button></Flex></Grid></Box>}
function Select({value,onChange,options=[]}:any){return <select value={value||''} onChange={e=>onChange(e.target.value)} style={{height:'40px',border:'1px solid #e2e8f0',borderRadius:'8px',padding:'0 10px',background:'white'}}><option value="">Todos</option>{options.map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select>}
function Kpi({title,value,detail,icon:Icon}:any){return <Box bg="white" borderWidth="1px" rounded="2xl" p="5"><Flex justify="space-between"><Box><Text color="gray.500" fontSize="sm">{title}</Text><Heading mt="2" size="lg">{value??0}</Heading><Text mt="2" color="gray.500" fontSize="sm">{detail}</Text></Box><Box color="blue.600"><Icon size={25}/></Box></Flex></Box>}
function Panel({title,children}:any){return <Box bg="white" borderWidth="1px" rounded="2xl" p="5" overflowX="auto"><Heading size="md" mb="4">{title}</Heading>{children}</Box>}
function Mini({label,value}:any){return <Box bg="gray.50" rounded="xl" p="3"><Text fontSize="xs" color="gray.500">{label}</Text><Text fontWeight="bold">{value}</Text></Box>}
function BarList({rows,moneyValues=false}:any){const max=Math.max(1,...rows.map((r:any)=>Number(r[1]||0)));return <VStack align="stretch" gap="3">{rows.map((r:any)=><Box key={r[0]}><Flex justify="space-between"><Text fontSize="sm">{r[0]}</Text><Text fontSize="sm" fontWeight="bold">{moneyValues?money(r[1]):r[1]||0}</Text></Flex><Box mt="1" h="7px" bg="gray.100" rounded="full"><Box h="full" w={`${Math.max(2,(Number(r[1]||0)/max)*100)}%`} bg="blue.500" rounded="full"/></Box></Box>)}</VStack>}
function Traffic({label,value,color}:any){return <Flex align="center" justify="space-between" py="2"><Flex align="center" gap="2"><Box w="12px" h="12px" rounded="full" bg={color}/><Text>{label}</Text></Flex><Text fontWeight="bold">{value||0}</Text></Flex>}
function Donut({value}:any){const safe=Math.min(100,Math.max(0,value));return <Flex mt="4" align="center" gap="4"><Box w="88px" h="88px" rounded="full" bg={`conic-gradient(#3182ce ${safe}%, #edf2f7 0)`} display="grid" placeItems="center"><Box w="60px" h="60px" bg="white" rounded="full" display="grid" placeItems="center"><Text fontWeight="bold">{safe}%</Text></Box></Box><Text fontSize="sm" color="gray.600">Reservado y ejecutado sobre el presupuesto aprobado.</Text></Flex>}
function LineChart({rows}:any){const points=useMemo(()=>{const max=Math.max(1,...rows.map((x:any)=>x.count));return rows.map((x:any,i:number)=>`${rows.length===1?50:(i/(rows.length-1))*100},${90-(x.count/max)*75}`).join(' ')},[rows]);return rows.length?<Box><svg viewBox="0 0 100 100" width="100%" height="150" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#3182ce" strokeWidth="3" vectorEffect="non-scaling-stroke"/></svg><Flex justify="space-between"><Text fontSize="xs">{rows[0].period}</Text><Text fontSize="xs">{rows.at(-1).period}</Text></Flex></Box>:<Text color="gray.500">Sin datos para el perÃ­odo.</Text>}
function DataTable({rows,columns}:any){return <Table.Root size="sm"><Table.Header><Table.Row>{columns.map((c:any)=><Table.ColumnHeader key={c[0]}>{c[1]}</Table.ColumnHeader>)}</Table.Row></Table.Header><Table.Body>{rows.slice(0,10).map((r:any,i:number)=><Table.Row key={r.userId||r.label||i}>{columns.map((c:any)=><Table.Cell key={c[0]}>{['reserved','executed'].includes(c[0])?money(r[c[0]]):r[c[0]]??0}</Table.Cell>)}</Table.Row>)}</Table.Body></Table.Root>}

