import { Badge, Box, Button, Flex, Grid, Heading, Input, Spinner, Table, Text } from '@chakra-ui/react';
import { useEffect, useState } from 'react';
import { bankingApi } from '../../services/banking.service';
import { catalogsService } from '../../services/catalogs.service';

export function MyBankAccountsPage() {
  const [accounts,setAccounts]=useState<any[]>([]),[banks,setBanks]=useState<any[]>([]),[currencies,setCurrencies]=useState<any[]>([]); const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [form,setForm]=useState({bankId:'',accountType:'MONETARIA',accountNumber:'',holderName:'',currencyId:'',isDefault:false});
  const load=async()=>{const [a,b,c]=await Promise.all([bankingApi.accounts(),bankingApi.banks(),catalogsService.getCurrencies()]);setAccounts(a);setBanks(b);setCurrencies(c.filter((x:any)=>x.active));}; useEffect(()=>{void load();},[]);
  const create=async()=>{setBusy(true);setMessage('');try{await bankingApi.create(form);setForm({...form,accountNumber:'',holderName:'',isDefault:false});await load();}catch(e:any){setMessage(e.response?.data?.message||'No se pudo registrar la cuenta.');}finally{setBusy(false);}};
  return <Box p={6}><Heading size="lg">Mis cuentas bancarias</Heading><Text color="gray.600" mb={5}>Administra las cuentas donde Tesorería puede realizar tus desembolsos.</Text>
  <Box borderWidth="1px" borderRadius="md" p={5} mb={6}><Grid templateColumns={{base:'1fr',md:'repeat(3,1fr)'}} gap={3}><select value={form.bankId} onChange={e=>setForm({...form,bankId:e.target.value})}><option value="">Banco</option>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={form.accountType} onChange={e=>setForm({...form,accountType:e.target.value})}><option>AHORRO</option><option>MONETARIA</option><option>CORRIENTE</option><option>OTRO</option></select><Input placeholder="Número de cuenta" value={form.accountNumber} onChange={e=>setForm({...form,accountNumber:e.target.value})}/><Input placeholder="Titular" value={form.holderName} onChange={e=>setForm({...form,holderName:e.target.value})}/><select value={form.currencyId} onChange={e=>setForm({...form,currencyId:e.target.value})}><option value="">Moneda</option>{currencies.map(c=><option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}</select><label><input type="checkbox" checked={form.isDefault} onChange={e=>setForm({...form,isDefault:e.target.checked})}/> Predeterminada para esta moneda</label></Grid>{message&&<Text color="red.600" mt={3}>{message}</Text>}<Button mt={4} colorPalette="blue" disabled={busy||!form.bankId||!form.accountNumber||!form.holderName||!form.currencyId} onClick={create}>{busy?<Spinner size="sm"/>:'Registrar cuenta'}</Button></Box>
  <Table.Root variant="outline"><Table.Header><Table.Row><Table.ColumnHeader>Banco</Table.ColumnHeader><Table.ColumnHeader>Tipo</Table.ColumnHeader><Table.ColumnHeader>Cuenta</Table.ColumnHeader><Table.ColumnHeader>Titular</Table.ColumnHeader><Table.ColumnHeader>Moneda</Table.ColumnHeader><Table.ColumnHeader>Estado</Table.ColumnHeader><Table.ColumnHeader>Acciones</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{accounts.map(a=><Table.Row key={a.id}><Table.Cell>{a.bank.name}</Table.Cell><Table.Cell>{a.accountType}</Table.Cell><Table.Cell>{a.accountNumber}</Table.Cell><Table.Cell>{a.holderName}</Table.Cell><Table.Cell>{a.currency.code}{a.isDefault&&<Badge ml={2}>Predeterminada</Badge>}</Table.Cell><Table.Cell><Badge colorPalette={a.active?'green':'gray'}>{a.active?'ACTIVA':'INACTIVA'}</Badge></Table.Cell><Table.Cell><Flex gap={2}>{a.active&&<Button size="xs" onClick={async()=>{await bankingApi.update(a.id,{active:false,comment:'Desactivada por el titular'});await load();}}>Desactivar</Button>}{a.active&&!a.isDefault&&<Button size="xs" onClick={async()=>{await bankingApi.update(a.id,{isDefault:true,comment:'Marcada como predeterminada'});await load();}}>Predeterminada</Button>}</Flex></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box>;
}
