import { Box, Button, Flex, Grid, Input } from '@chakra-ui/react';
import type { ReportCatalogs, ReportFilters, ReportKind } from '../types/reports.types';

type Props = { kind: ReportKind; value: ReportFilters; catalogs: ReportCatalogs | null; onChange: (value: Partial<ReportFilters>) => void; onApply: () => void; onClear: () => void };
export function ReportFiltersPanel({ kind, value, catalogs, onChange, onApply, onClear }: Props) {
  const field = (key: keyof ReportFilters, input: string | number | undefined) => onChange({ [key]: input || undefined, page: 1 });
  const option = (items: Array<{ id: string; name: string }> = []) => items.map((item) => <option key={item.id} value={item.id}>{item.name}</option>);
  const selectStyle = { height: '40px', border: '1px solid #e2e8f0', borderRadius: '8px', padding: '0 10px', background: 'white', width: '100%' };
  const budget = kind === 'budget'; const requests = kind === 'requests';
  return <Box bg="white" borderWidth="1px" rounded="2xl" p="4">
    <Grid templateColumns={{ base: '1fr', md: 'repeat(3,1fr)', xl: 'repeat(5,1fr)' }} gap="3">
      <select aria-label="Empresa" style={selectStyle} value={value.companyId || ''} onChange={(e) => field('companyId', e.target.value)}><option value="">Todas las empresas</option>{option(catalogs?.companies)}</select>
      {(budget || kind === 'executive') && <select aria-label="País" style={selectStyle} value={value.countryId || ''} onChange={(e) => field('countryId', e.target.value)}><option value="">Todos los países</option>{option(catalogs?.countries)}</select>}
      {budget && <><select aria-label="Unidad de negocio" style={selectStyle} value={value.businessUnit || ''} onChange={(e) => field('businessUnit', e.target.value)}><option value="">Todas las unidades</option>{[...new Set(catalogs?.dimensions.map((x) => x.businessUnit) || [])].sort().map((x) => <option key={x}>{x}</option>)}</select><select aria-label="Área" style={selectStyle} value={value.area || ''} onChange={(e) => field('area', e.target.value)}><option value="">Todas las áreas</option>{[...new Set(catalogs?.dimensions.map((x) => x.area) || [])].sort().map((x) => <option key={x}>{x}</option>)}</select><select aria-label="Año" style={selectStyle} value={value.year || ''} onChange={(e) => field('year', e.target.value ? Number(e.target.value) : undefined)}><option value="">Todos los años</option>{catalogs?.years.map((x) => <option key={x}>{x}</option>)}</select><select aria-label="Cuenta" style={selectStyle} value={value.account || ''} onChange={(e) => field('account', e.target.value)}><option value="">Todas las cuentas</option>{[...new Map((catalogs?.dimensions || []).map((x) => [x.accountCode, x])).values()].sort((a,b)=>a.accountCode.localeCompare(b.accountCode)).map((x) => <option key={x.accountCode} value={x.accountCode}>{x.accountCode} - {x.accountDescription}</option>)}</select></>}
      {(requests || kind === 'executive') && <><select aria-label="Estado" style={selectStyle} value={value.status || ''} onChange={(e) => field('status', e.target.value)}><option value="">Todos los estados</option>{catalogs?.statuses.map((x) => <option key={x}>{x}</option>)}</select><select aria-label="Solicitante" style={selectStyle} value={value.requesterId || ''} onChange={(e) => field('requesterId', e.target.value)}><option value="">Todos los solicitantes</option>{option(catalogs?.users)}</select><select aria-label="Tipo de gasto" style={selectStyle} value={value.expenseType || ''} onChange={(e) => field('expenseType', e.target.value)}><option value="">Todos los tipos</option>{catalogs?.expenseTypes.map((x) => <option key={x}>{x}</option>)}</select><Input aria-label="Centro de costo" placeholder="Centro de costo" value={value.costCenter || ''} onChange={(e) => field('costCenter', e.target.value)} /></>}
      {!budget && <><Input aria-label="Fecha inicial" type="date" value={value.dateFrom || ''} onChange={(e) => field('dateFrom', e.target.value)} /><Input aria-label="Fecha final" type="date" value={value.dateTo || ''} onChange={(e) => field('dateTo', e.target.value)} /></>}
      <Flex gap="2"><Button flex="1" colorPalette="blue" onClick={onApply}>Aplicar</Button><Button variant="outline" onClick={onClear}>Limpiar</Button></Flex>
    </Grid>
  </Box>;
}
