import { useEffect, useState } from 'react';
import { Badge, Box, Button, Flex, Grid, Heading, Input, Table, Text, VStack } from '@chakra-ui/react';
import { catalogsService, type Currency } from '../../services/catalogs.service';
import { exchangeRatesService, type ExchangeRate } from '../../services/exchangeRates.service';

const emptyCurrency = { code: '', name: '', symbol: '' };
const emptyRate = () => ({ fromCurrencyId: '', toCurrencyId: '', rate: '', effectiveDate: new Date().toISOString().slice(0, 10) });

export function CurrenciesExchangeRatesPage() {
  const [currencies, setCurrencies] = useState<Currency[]>([]), [rates, setRates] = useState<ExchangeRate[]>([]);
  const [currency, setCurrency] = useState(emptyCurrency), [rate, setRate] = useState(emptyRate());
  const [editingRateId, setEditingRateId] = useState<string | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('');
  const load = async () => { try { const [currencyRows, rateRows] = await Promise.all([catalogsService.getCurrencies(true), exchangeRatesService.list()]); setCurrencies(currencyRows); setRates(rateRows); } catch (error: any) { setMessage(error.response?.data?.message || 'No fue posible cargar la configuración monetaria.'); } };
  useEffect(() => { void load(); }, []);
  const createCurrency = async () => { setBusy(true); try { await catalogsService.createCurrency(currency); setCurrency(emptyCurrency); setMessage('Moneda creada.'); await load(); } catch (error: any) { setMessage(error.response?.data?.message || 'No fue posible crear la moneda.'); } finally { setBusy(false); } };
  const saveRate = async () => { setBusy(true); try { if (editingRateId) await exchangeRatesService.update(editingRateId, { rate: rate.rate, effectiveDate: rate.effectiveDate }); else await exchangeRatesService.create(rate); setEditingRateId(null); setRate(emptyRate()); setMessage(editingRateId ? 'Tasa modificada y auditada.' : 'Tasa registrada. Las operaciones históricas conservarán su tasa anterior.'); await load(); } catch (error: any) { setMessage(error.response?.data?.message || 'No fue posible guardar la tasa.'); } finally { setBusy(false); } };
  const edit = (item: ExchangeRate) => { setEditingRateId(item.id); setRate({ fromCurrencyId: item.fromCurrencyId, toCurrencyId: item.toCurrencyId, rate: String(item.rate), effectiveDate: item.effectiveDate.slice(0, 10) }); };
  const cancelEdit = () => { setEditingRateId(null); setRate(emptyRate()); };
  const toggleCurrency = async (item: Currency) => { await catalogsService.updateCurrency(item.id, { active: !item.active }); await load(); };
  const toggleRate = async (item: ExchangeRate) => { await exchangeRatesService.update(item.id, { active: !item.active }); await load(); };
  return <VStack align="stretch" gap="5" p={{ base: '4', md: '8' }}>
    <Box><Heading size="lg">Monedas y tasas de cambio</Heading><Text color="gray.600">Administración manual y auditable. Los códigos deben seguir ISO 4217.</Text></Box>
    {message && <Box p="3" rounded="lg" bg="blue.50" color="blue.800">{message}</Box>}
    <Grid templateColumns={{ base: '1fr', xl: '1fr 1.4fr' }} gap="5">
      <Box bg="white" borderWidth="1px" rounded="2xl" p="5"><Heading size="md" mb="4">Nueva moneda</Heading><Grid templateColumns="100px 1fr 100px" gap="2"><Input placeholder="USD" value={currency.code} onChange={(e) => setCurrency({ ...currency, code: e.target.value.toUpperCase() })}/><Input placeholder="Nombre" value={currency.name} onChange={(e) => setCurrency({ ...currency, name: e.target.value })}/><Input placeholder="Símbolo" value={currency.symbol} onChange={(e) => setCurrency({ ...currency, symbol: e.target.value })}/></Grid><Button mt="3" colorPalette="blue" loading={busy} disabled={!currency.code || !currency.name || !currency.symbol} onClick={createCurrency}>Crear moneda</Button><Table.Root size="sm" mt="4"><Table.Header><Table.Row><Table.ColumnHeader>Código</Table.ColumnHeader><Table.ColumnHeader>Nombre</Table.ColumnHeader><Table.ColumnHeader>Estado</Table.ColumnHeader><Table.ColumnHeader/></Table.Row></Table.Header><Table.Body>{currencies.map((item) => <Table.Row key={item.id}><Table.Cell>{item.symbol} {item.code}</Table.Cell><Table.Cell>{item.name}</Table.Cell><Table.Cell><State active={item.active}/></Table.Cell><Table.Cell><Button size="xs" variant="outline" onClick={() => void toggleCurrency(item)}>{item.active ? 'Desactivar' : 'Activar'}</Button></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box>
      <Box bg="white" borderWidth="1px" rounded="2xl" p="5"><Heading size="md" mb="4">{editingRateId ? 'Editar tasa' : 'Nueva tasa'}</Heading><Grid templateColumns={{ base: '1fr 1fr', md: '1fr 1fr 140px 160px' }} gap="2"><CurrencySelect value={rate.fromCurrencyId} currencies={currencies} label="Moneda origen" disabled={!!editingRateId} onChange={(value) => setRate({ ...rate, fromCurrencyId: value })}/><CurrencySelect value={rate.toCurrencyId} currencies={currencies} label="Moneda destino" disabled={!!editingRateId} onChange={(value) => setRate({ ...rate, toCurrencyId: value })}/><Input aria-label="Tasa" placeholder="7.8000000000" inputMode="decimal" value={rate.rate} onChange={(e) => setRate({ ...rate, rate: e.target.value })}/><Input aria-label="Fecha efectiva" type="date" value={rate.effectiveDate} onChange={(e) => setRate({ ...rate, effectiveDate: e.target.value })}/></Grid><Flex mt="3" gap="2"><Button colorPalette="blue" loading={busy} disabled={!rate.fromCurrencyId || !rate.toCurrencyId || !rate.rate || rate.fromCurrencyId === rate.toCurrencyId} onClick={saveRate}>{editingRateId ? 'Guardar cambios' : 'Registrar tasa'}</Button>{editingRateId && <Button variant="outline" onClick={cancelEdit}>Cancelar</Button>}</Flex><Box overflowX="auto"><Table.Root size="sm" mt="4"><Table.Header><Table.Row><Table.ColumnHeader>Conversión</Table.ColumnHeader><Table.ColumnHeader>Tasa</Table.ColumnHeader><Table.ColumnHeader>Vigente desde</Table.ColumnHeader><Table.ColumnHeader>Estado</Table.ColumnHeader><Table.ColumnHeader/></Table.Row></Table.Header><Table.Body>{rates.map((item) => <Table.Row key={item.id}><Table.Cell>{item.fromCurrency.code} → {item.toCurrency.code}</Table.Cell><Table.Cell>{Number(item.rate).toLocaleString('es-GT', { maximumFractionDigits: 10 })}</Table.Cell><Table.Cell>{item.effectiveDate.slice(0, 10)}</Table.Cell><Table.Cell><State active={item.active}/></Table.Cell><Table.Cell><Flex gap="2"><Button size="xs" variant="outline" onClick={() => edit(item)}>Editar</Button><Button size="xs" variant="outline" onClick={() => void toggleRate(item)}>{item.active ? 'Desactivar' : 'Activar'}</Button></Flex></Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box></Box>
    </Grid>
  </VStack>;
}
function State({ active }: { active: boolean }) { return <Badge colorPalette={active ? 'green' : 'gray'}>{active ? 'Activa' : 'Inactiva'}</Badge>; }
function CurrencySelect({ value, currencies, label, disabled, onChange }: { value: string; currencies: Currency[]; label: string; disabled?: boolean; onChange: (value: string) => void }) { return <select aria-label={label} disabled={disabled} style={{ height: '40px', border: '1px solid #CBD5E0', borderRadius: '8px', padding: '0 10px' }} value={value} onChange={(event) => onChange(event.target.value)}><option value="">{label}</option>{currencies.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.code} - {item.name}</option>)}</select>; }
