import { useEffect, useMemo, useState } from 'react';
import { Badge, Box, Button, Flex, Grid, Heading, Spinner, Table, Text, VStack } from '@chakra-ui/react';
import { Download } from 'lucide-react';
import { useAppDispatch, useAppSelector } from '../../hooks/redux';
import { clearFilters, exportReport, initializeReport, loadReport, loadReportCatalogs, setFilters } from '../../store/reports.slice';
import type { ReportFilters } from '../../modules/reports/types/reports.types';
import { ReportFiltersPanel } from '../../modules/reports/components/ReportFilters';

const money = (value: number) => new Intl.NumberFormat('es-GT', { style: 'currency', currency: 'USD' }).format(value || 0);
export function ExecutiveReportPage() {
  const dispatch = useAppDispatch(); const state = useAppSelector((root) => root.reports); const [draft, setDraft] = useState<ReportFilters>(state.filters); const [sortAsc, setSortAsc] = useState(true); const [page, setPage] = useState(1);
  useEffect(() => { dispatch(initializeReport('executive')); dispatch(loadReportCatalogs()).then(() => dispatch(loadReport())); }, [dispatch]);
  useEffect(() => { setDraft(state.filters); }, [state.filters]);
  const data = state.executive;
  const indicators = useMemo(() => data ? [{ indicator: 'Presupuesto utilizado', value: data.budget.executed, display: money(data.budget.executed) }, { indicator: 'Presupuesto disponible', value: data.budget.available, display: money(data.budget.available) }, { indicator: 'Solicitudes', value: data.summary.total, display: data.summary.total }, { indicator: 'Aprobaciones', value: data.summary.approved, display: data.summary.approved }, { indicator: 'SLA vencidas', value: data.workflow.overdueRequests, display: data.workflow.overdueRequests }, { indicator: 'Incumplimientos', value: data.policies.violations, display: data.policies.violations }].sort((a, b) => sortAsc ? a.indicator.localeCompare(b.indicator) : b.indicator.localeCompare(a.indicator)) : [], [data, sortAsc]);
  const apply = () => { dispatch(setFilters(draft)); setTimeout(() => dispatch(loadReport()), 0); };
  return <VStack align="stretch" gap="5"><Flex justify="space-between" align={{ base: 'start', md: 'center' }} direction={{ base: 'column', md: 'row' }} gap="3"><Box><Badge colorPalette="blue">Dirección Financiera</Badge><Heading mt="2" size="lg">Reporte Ejecutivo</Heading><Text color="gray.500">Resumen consolidado de presupuesto, solicitudes, aprobaciones, SLA y políticas.</Text></Box><Flex gap="2"><Button variant="outline" disabled={state.exporting} onClick={() => dispatch(exportReport('excel'))}><Download size={16}/>Excel</Button><Button variant="outline" disabled={state.exporting} onClick={() => dispatch(exportReport('pdf'))}><Download size={16}/>PDF</Button></Flex></Flex>
    <ReportFiltersPanel kind="executive" value={draft} catalogs={state.catalogs} onChange={(value) => setDraft({ ...draft, ...value })} onApply={apply} onClear={() => { dispatch(clearFilters()); setTimeout(() => dispatch(loadReport()), 0); }}/>
    {state.loading && <Flex justify="center" py="12"><Spinner size="xl"/></Flex>}{state.error && <Box bg="red.50" color="red.700" p="4" rounded="xl">{state.error}</Box>}
    {data && !state.loading && <><Grid templateColumns={{ base: '1fr', md: 'repeat(3,1fr)', xl: 'repeat(6,1fr)' }} gap="3">{indicators.map((item) => <Box key={item.indicator} bg="white" borderWidth="1px" rounded="2xl" p="4"><Text fontSize="xs" color="gray.500">{item.indicator}</Text><Heading size="md" mt="2">{item.display}</Heading></Box>)}</Grid>
      <Grid templateColumns={{ base: '1fr', xl: '1fr 1fr' }} gap="5"><Chart title="Estados de solicitudes" rows={[['Pendientes', data.summary.pending], ['Aprobadas', data.summary.approved], ['Rechazadas', data.summary.rejected], ['Observadas', data.summary.observed]]}/><Chart title="Semáforo SLA" rows={[['Verde', data.workflow.sla.green], ['Amarillo', data.workflow.sla.yellow], ['Rojo', data.workflow.sla.red], ['Vencidas', data.workflow.sla.expired]]}/><Chart title="Ejecución presupuestaria" rows={[['Utilizado', data.budget.executed], ['Comprometido', data.budget.reserved], ['Disponible', data.budget.available]]}/><Chart title="Cumplimiento de políticas" rows={[['Advertencias', data.policies.warnings], ['Incumplimientos', data.policies.violations], ['Requieren aprobación', data.policies.approvalRequired], ['Cumplen', data.policies.ok]]}/></Grid>
      <Box bg="white" borderWidth="1px" rounded="2xl" overflowX="auto"><Table.Root size="sm"><Table.Header><Table.Row><Table.ColumnHeader><Button size="xs" variant="ghost" onClick={() => setSortAsc(!sortAsc)}>Indicador ↕</Button></Table.ColumnHeader><Table.ColumnHeader>Valor</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{indicators.slice((page - 1) * 5, page * 5).map((item) => <Table.Row key={item.indicator}><Table.Cell>{item.indicator}</Table.Cell><Table.Cell>{item.display}</Table.Cell></Table.Row>)}</Table.Body></Table.Root><Flex justify="space-between" p="4"><Text fontSize="sm">Página {page} de 2</Text><Flex gap="2"><Button size="sm" variant="outline" disabled={page === 1} onClick={() => setPage(1)}>Anterior</Button><Button size="sm" variant="outline" disabled={page === 2} onClick={() => setPage(2)}>Siguiente</Button></Flex></Flex></Box></>}
  </VStack>;
}
function Chart({ title, rows }: { title: string; rows: Array<[string, number]> }) { const max = Math.max(1, ...rows.map((row) => Number(row[1] || 0))); return <Box bg="white" borderWidth="1px" rounded="2xl" p="5"><Heading size="sm" mb="4">{title}</Heading><VStack align="stretch" gap="3">{rows.map(([label, value]) => <Box key={label}><Flex justify="space-between"><Text fontSize="sm">{label}</Text><Text fontWeight="bold">{Number(value || 0).toLocaleString('es-GT')}</Text></Flex><Box mt="1" h="8px" bg="gray.100" rounded="full"><Box h="full" w={`${Math.max(2, Number(value || 0) / max * 100)}%`} bg="blue.500" rounded="full"/></Box></Box>)}</VStack></Box>; }
