import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { FunctionalTestCaseStatus, FunctionalTestRecordStatus, FunctionalTestResult } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { CreateTestCaseDto, CreateTestRecordDto, ExecuteTestCaseDto, UpdateTestCaseDto, UpdateTestRecordDto } from './dto/functional-test.dto';

@Injectable()
export class FunctionalTestsService {
  constructor(private readonly prisma: PrismaService) {}
  private scope(user:any, companyId?:string) { if (!user?.id) throw new ForbiddenException('Usuario no autenticado.'); if (user.role==='ADMIN') return companyId ? { companyId } : {}; if (!user.companyId) throw new ForbiddenException('Usuario sin empresa.'); if (companyId && companyId!==user.companyId) throw new ForbiddenException('No tiene acceso a esta empresa.'); return { companyId:user.companyId }; }
  private async record(id:string,user:any) { const r=await this.prisma.functionalTestRecord.findUnique({where:{id},include:{cases:{include:{requirement:true,evidence:{include:{document:true}}},orderBy:{createdAt:'asc'}},company:true,createdBy:true}}); if(!r) throw new NotFoundException('Registro de pruebas no encontrado.'); if(user.role!=='ADMIN' && r.companyId!==user.companyId) throw new ForbiddenException('No tiene acceso a este registro.'); return r; }
  private ensureEditable(r:any) { if(r.status===FunctionalTestRecordStatus.CERRADO) throw new BadRequestException('El registro de pruebas está cerrado.'); }
  async create(dto:CreateTestRecordDto,user:any) { const companyId=dto.companyId || user.companyId; this.scope(user,companyId); return this.prisma.functionalTestRecord.create({data:{project:dto.project,analystName:dto.analystName,performedByName:dto.performedByName,startedAt:new Date(dto.startedAt),comments:dto.comments,companyId,createdByUserId:user.id}}); }
  async list(user:any) { return this.prisma.functionalTestRecord.findMany({where:this.scope(user),include:{cases:{select:{status:true,result:true}},createdBy:{select:{id:true,name:true}},company:true},orderBy:{createdAt:'desc'}}).then(rows=>rows.map(r=>this.summaryRow(r))); }
  async get(id:string,user:any) { return this.record(id,user); }
  async update(id:string,dto:UpdateTestRecordDto,user:any) { const r=await this.record(id,user); this.ensureEditable(r); return this.prisma.functionalTestRecord.update({where:{id},data:{...dto,startedAt:dto.startedAt?new Date(dto.startedAt):undefined}}); }
  async close(id:string,user:any) { const r=await this.record(id,user); this.ensureEditable(r); const summary=await this.summary(id,user); if(summary.pending>0) throw new BadRequestException('No se puede cerrar con casos pendientes.'); return this.prisma.functionalTestRecord.update({where:{id},data:{status:FunctionalTestRecordStatus.CERRADO}}); }
  async addCase(recordId:string,dto:CreateTestCaseDto,user:any) { const r=await this.record(recordId,user); this.ensureEditable(r); const req=await this.prisma.functionalRequirement.upsert({where:{code_name:{code:dto.requirementCode,name:dto.requirementName}},create:{code:dto.requirementCode,name:dto.requirementName,description:dto.description},update:{description:dto.description}}); return this.prisma.functionalTestCase.create({data:{recordId,requirementId:req.id,testDescription:dto.testDescription,acceptanceCriteria:dto.acceptanceCriteria,estimatedTime:dto.estimatedTime}}); }
  async updateCase(id:string,dto:UpdateTestCaseDto,user:any) { const c=await this.prisma.functionalTestCase.findUnique({where:{id},include:{record:true}}); if(!c) throw new NotFoundException('Caso de prueba no encontrado.'); await this.record(c.recordId,user); this.ensureEditable(c.record); if(dto.result && dto.status!==FunctionalTestCaseStatus.REALIZADA && c.status!==FunctionalTestCaseStatus.REALIZADA) throw new BadRequestException('Un resultado requiere una prueba realizada.'); if(dto.status===FunctionalTestCaseStatus.REALIZADA && !dto.result && !c.result) throw new BadRequestException('Una prueba realizada requiere resultado.'); if(dto.result===FunctionalTestResult.NO_EXITOSA && !dto.observations && !c.observations) throw new BadRequestException('Una prueba no exitosa requiere observación.'); return this.prisma.functionalTestCase.update({where:{id},data:{...dto,testDate:dto.testDate?new Date(dto.testDate):undefined}}); }
  async execute(id:string,dto:ExecuteTestCaseDto,user:any) { const c=await this.prisma.functionalTestCase.findUnique({where:{id},include:{record:true}}); if(!c) throw new NotFoundException('Caso de prueba no encontrado.'); await this.record(c.recordId,user); this.ensureEditable(c.record); if(dto.result===FunctionalTestResult.NO_EXITOSA && !dto.observations) throw new BadRequestException('Una prueba no exitosa requiere observación.'); const now=new Date(); const updated=await this.prisma.functionalTestCase.update({where:{id},data:{status:FunctionalTestCaseStatus.REALIZADA,result:dto.result,observedResult:dto.observedResult,observations:dto.observations,testDate:dto.testDate?new Date(dto.testDate):now,executedAt:now,executedByUserId:user.id}}); await this.prisma.securityAudit.create({data:{userId:user.id,actorUserId:user.id,action:'FUNCTIONAL_TEST_EXECUTED',result:dto.result,comment:`Caso ${id} ejecutado`}}); return updated; }
  async addEvidence(caseId:string,documentId:string,user:any) { const c=await this.prisma.functionalTestCase.findUnique({where:{id:caseId},include:{record:true}}); if(!c) throw new NotFoundException('Caso de prueba no encontrado.'); await this.record(c.recordId,user); const d=await this.prisma.document.findUnique({where:{id:documentId},include:{user:true}}); if(!d) throw new NotFoundException('Evidencia no encontrada.'); if(user.role!=='ADMIN' && d.user.companyId!==user.companyId) throw new ForbiddenException('No tiene acceso a la evidencia.'); return this.prisma.functionalTestEvidence.create({data:{testCaseId:caseId,documentId,uploadedByUserId:user.id}}); }
  async summary(id:string,user:any) { const r=await this.record(id,user); const total=r.cases.length; const performed=r.cases.filter(c=>c.status===FunctionalTestCaseStatus.REALIZADA).length; const successful=r.cases.filter(c=>c.result===FunctionalTestResult.EXITOSA).length; const failed=r.cases.filter(c=>c.result===FunctionalTestResult.NO_EXITOSA).length; return {total,performed,pending:total-performed,successful,failed,performedPercentage:total?Number((performed/total*100).toFixed(2)):0,successfulPercentage:performed?Number((successful/performed*100).toFixed(2)):0}; }
  private summaryRow(r:any) { const total=r.cases.length, performed=r.cases.filter((c:any)=>c.status===FunctionalTestCaseStatus.REALIZADA).length, successful=r.cases.filter((c:any)=>c.result===FunctionalTestResult.EXITOSA).length, failed=r.cases.filter((c:any)=>c.result===FunctionalTestResult.NO_EXITOSA).length; return {...r,total,performed,pending:total-performed,successful,failed,performedPercentage:total?Number((performed/total*100).toFixed(2)):0,successfulPercentage:performed?Number((successful/performed*100).toFixed(2)):0}; }
}
