import { authorizedCompanyId, hasPermission } from '../auth/permissions.util';
import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { BudgetReservationStatus, BudgetVersionStatus, Prisma } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { AvailableBudgetQueryDto, BudgetQueryDto } from './dto/budget-query.dto';

@Injectable()
export class BudgetQueryService {
  constructor(private readonly prisma: PrismaService) {}
  async list(query: BudgetQueryDto, user: any) { this.assertFinancialRead(user); query = { ...query, companyId: authorizedCompanyId(user, query.companyId) }; const where = this.where(query); const allowed = new Set(['accountCode', 'businessUnit', 'area', 'annualAmount', 'sourceRow']); const sortBy = allowed.has(query.sortBy) ? query.sortBy : 'accountCode'; const [lines, total] = await Promise.all([this.prisma.budgetLine.findMany({ where, skip: (query.page - 1) * query.pageSize, take: query.pageSize, orderBy: { [sortBy]: query.sortOrder === 'desc' ? 'desc' : 'asc' }, include: this.include(query.month) }), this.prisma.budgetLine.count({ where })]); return { data: lines.map((line) => this.format(line, query.month)), meta: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.max(1, Math.ceil(total / query.pageSize)) } }; }
  async detail(id: string, user: any) { this.assertFinancialRead(user); const companyId = authorizedCompanyId(user); const line = await this.prisma.budgetLine.findFirst({ where: { id, companyId }, include: { ...this.include(), reservations: { include: { budgetPeriod: { select: { id: true, month: true, fiscalYear: true } } }, orderBy: { reservedAt: 'desc' } }, selectedRequests: { select: { id: true, code: true, createdAt: true, requesterName: true, estimatedAmount: true, status: true, currency: true, budgetPeriod: { select: { month: true } }, budgetReservations: { where: { budgetLineId: id }, orderBy: { createdAt: 'desc' } } }, orderBy: { createdAt: 'desc' } } } }); if (!line) throw new NotFoundException('Partida presupuestaria no encontrada.'); return { ...this.format(line), relatedRequests: line.selectedRequests.map((request) => { const reservation = request.budgetReservations[0]; return { reservationId: reservation?.id || `draft-${request.id}`, requestId: request.id, number: request.code, date: request.createdAt, requester: request.requesterName, requestedAmount: Number(request.estimatedAmount), committedAmount: reservation && reservation.status !== BudgetReservationStatus.RELEASED ? Number(reservation.amount) : 0, currency: request.currency, requestStatus: request.status, reservationStatus: reservation?.status || 'SIN_RESERVA', month: request.budgetPeriod?.month || null }; }) }; }
  async available(query: AvailableBudgetQueryDto, user: any) { query = { ...query, companyId: authorizedCompanyId(user, query.companyId)! }; const date = query.estimatedDate ? new Date(`${query.estimatedDate}T12:00:00`) : new Date(); if (Number.isNaN(date.getTime())) throw new BadRequestException('La fecha estimada no es válida.'); const year = date.getFullYear(), month = date.getMonth() + 1; const lines = await this.prisma.budgetLine.findMany({ where: { version: { fiscalYear: year, active: true, status: BudgetVersionStatus.ACTIVE }, countryId: query.countryId, OR: [{ companyId: query.companyId }, { companyId: null }] }, include: this.include(month), orderBy: [{ area: 'asc' }, { accountCode: 'asc' }] }); return { year, month, data: lines.map((line) => this.format(line, month)).filter((line) => line.periodId && line.monthlyAvailable > 0) }; }
  async filters(user: any) { this.assertFinancialRead(user); const companyId = authorizedCompanyId(user); const [versions, companies, countries, dimensions] = await Promise.all([this.prisma.budgetVersion.findMany({ where: companyId ? { lines: { some: { companyId } } } : undefined, select: { id: true, fiscalYear: true, versionNumber: true, status: true, active: true }, orderBy: [{ fiscalYear: 'desc' }, { versionNumber: 'desc' }] }), this.prisma.company.findMany({ where: { active: true, id: companyId }, select: { id: true, name: true }, orderBy: { name: 'asc' } }), this.prisma.country.findMany({ where: { active: true }, select: { id: true, name: true }, orderBy: { name: 'asc' } }), this.prisma.budgetLine.findMany({ where: { companyId }, distinct: ['businessUnit', 'area', 'accountCode'], select: { businessUnit: true, area: true, accountCode: true, accountDescription: true } })]); return { versions, companies, countries, dimensions, statuses: Object.values(BudgetVersionStatus), months: Array.from({ length: 12 }, (_, index) => index + 1) }; }
  private where(query: BudgetQueryDto): Prisma.BudgetLineWhereInput { return { versionId: query.versionId || undefined, version: { fiscalYear: query.year, status: query.status, active: query.versionId || query.status ? undefined : true }, companyId: query.companyId || undefined, countryId: query.countryId || undefined, businessUnit: query.businessUnit ? { contains: query.businessUnit, mode: 'insensitive' } : undefined, area: query.area ? { contains: query.area, mode: 'insensitive' } : undefined, accountCode: query.account ? { contains: query.account, mode: 'insensitive' } : undefined, periods: query.month ? { some: { month: query.month } } : undefined }; }
  private include(month?: number) { return { version: { select: { id: true, fiscalYear: true, versionNumber: true, status: true, active: true } }, company: { select: { id: true, name: true } }, country: { select: { id: true, name: true } }, periods: { where: month ? { month } : undefined, orderBy: { month: 'asc' as const } }, reservations: { where: { status: { in: [BudgetReservationStatus.RESERVED, BudgetReservationStatus.EXECUTED] } }, select: { amount: true, status: true, budgetPeriodId: true } } }; }
  private format(line: any, month?: number) { const reserved = this.sum(line.reservations.filter((item: any) => item.status === BudgetReservationStatus.RESERVED)); const executed = this.sum(line.reservations.filter((item: any) => item.status === BudgetReservationStatus.EXECUTED)); const annual = Number(line.annualAmount); const periods = line.periods.map((period: any) => { const periodReserved = this.sum(line.reservations.filter((item: any) => item.budgetPeriodId === period.id && item.status === BudgetReservationStatus.RESERVED)); const periodExecuted = this.sum(line.reservations.filter((item: any) => item.budgetPeriodId === period.id && item.status === BudgetReservationStatus.EXECUTED)); const approved = Number(period.approvedAmount); return { id: period.id, month: period.month, approved, committed: periodReserved, executed: periodExecuted, available: this.round(approved - periodReserved - periodExecuted) }; }); const selected = month ? periods.find((period: any) => period.month === month) : undefined; return { id: line.id, version: line.version, company: line.company, country: line.country, businessUnit: line.businessUnit, area: line.area, accountCode: line.accountCode, accountDescription: line.accountDescription, detailDescription: line.detailDescription, currency: line.currency, annualBudget: annual, committed: reserved, executed, available: this.round(annual - reserved - executed), periods, periodId: selected?.id || null, month: selected?.month || null, monthlyBudget: selected?.approved || 0, monthlyCommitted: selected?.committed || 0, monthlyExecuted: selected?.executed || 0, monthlyAvailable: selected?.available || 0 }; }
  private sum(rows: any[]) { return this.round(rows.reduce((sum, row) => sum + Number(row.amount || 0), 0)); }
  private round(value: number) { return Math.round((value + Number.EPSILON) * 100) / 100; }
  async assertRequestAccess(id: string, user: any) {
    const companyId = authorizedCompanyId(user);
    const global = user.role === 'ADMIN' || hasPermission(user, 'EXPENSE_REQUEST_VIEW_ALL');
    const team = hasPermission(user, 'EXPENSE_REQUEST_VIEW_TEAM') ? await this.prisma.user.findMany({ where: { managerId: user.id, companyId }, select: { id: true } }) : [];
    const scope: Prisma.ExpenseRequestWhereInput = global ? {} : hasPermission(user, 'EXPENSE_REQUEST_VIEW_COMPANY') ? { companyId } : {
      companyId, OR: [
        ...(hasPermission(user, 'EXPENSE_REQUEST_VIEW_OWN') || hasPermission(user, 'EXPENSE_REQUEST_VIEW_TEAM') ? [{ requesterId: user.id }] : []),
        ...(hasPermission(user, 'EXPENSE_REQUEST_VIEW_TEAM') ? [{ requesterId: { in: team.map(member => member.id) } }] : []),
      ],
    };
    if (!await this.prisma.expenseRequest.findFirst({ where: { AND: [{ id }, scope] }, select: { id: true } })) throw new NotFoundException('Solicitud no encontrada.');
  }
  private assertFinancialRead(user: any) {
    if (!['ADMIN', 'FINANZAS'].includes(user?.role) && !hasPermission(user, 'EXPENSE_REQUEST_VIEW_ALL')) throw new ForbiddenException('No tiene permiso para consultar el detalle financiero.');
  }
}
