import { useEffect, useMemo, useState } from 'react';
import { Badge, Box, Button, Flex, Grid, Heading, Spinner, Table, Text, VStack } from '@chakra-ui/react';
import { ChevronDown, ChevronUp, RefreshCw, X } from 'lucide-react';
import { getBudgetFilters, getBudgetLine, getBudgetLines } from '../../services/budget.service';

const money = (value: number, currency = 'USD') => new Intl.NumberFormat('es-GT', { style: 'currency', currency }).format(value || 0);
const monthNames = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];
const initial = { page: 1, pageSize: 20, sortBy: 'accountCode', sortOrder: 'asc' };

export function BudgetControlPage() {
  const [filters, setFilters] = useState<any>(initial); const [draft, setDraft] = useState<any>(initial); const [catalogs, setCatalogs] = useState<any>(); const [result, setResult] = useState<any>(); const [detail, setDetail] = useState<any>(); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async (next = filters) => { setLoading(true); setError(''); try { setResult(await getBudgetLines(next)); } catch (e:any) { setError(e.response?.data?.message || 'No fue posible consultar el presupuesto.'); } finally { setLoading(false); } };
  useEffect(() => { getBudgetFilters().then(setCatalogs).catch(() => setError('No fue posible cargar los filtros.')); void load(initial); }, []);
  const totals = useMemo(() => (result?.data || []).reduce((sum:any, row:any) => ({ annual: sum.annual + row.annualBudget, committed: sum.committed + row.committed, executed: sum.executed + row.executed, available: sum.available + row.available }), { annual: 0, committed: 0, executed: 0, available: 0 }), [result]);
  const update = (key:string, value:any) => setDraft((current:any) => ({ ...current, [key]: value || undefined, page: 1 }));
  const apply = () => { setFilters(draft); void load(draft); }; const page = (value:number) => { const next={...filters,page:value};setFilters(next);setDraft(next);void load(next); };
  const sort = (key:string) => { const next={...filters,sortBy:key,sortOrder:filters.sortBy===key&&filters.sortOrder==='asc'?'desc':'asc',page:1};setFilters(next);setDraft(next);void load(next); };
  const open = async (id:string) => { try { setDetail(await getBudgetLine(id)); } catch { setError('No fue posible cargar el detalle de la partida.'); } };
  const selectStyle={height:'40px',border:'1px solid #e2e8f0',borderRadius:'8px',padding:'0 10px',background:'white',width:'100%'};
  return <VStack align="stretch" gap="5"><Flex justify="space-between" align={{base:'start',md:'center'}} direction={{base:'column',md:'row'}}><Box><Badge colorPalette="blue">Presupuesto OPEX</Badge><Heading mt="2" size="lg">Control Presupuestario</Heading><Text color="gray.500">Partidas, períodos, compromisos y ejecución obtenidos desde PostgreSQL.</Text></Box><Button variant="outline" onClick={()=>load()}><RefreshCw size={16}/>Actualizar</Button></Flex>
    <Box bg="white" borderWidth="1px" rounded="2xl" p="4"><Grid templateColumns={{base:'1fr',md:'repeat(4,1fr)',xl:'repeat(8,1fr)'}} gap="3">
      <select style={selectStyle} value={draft.versionId||''} onChange={e=>update('versionId',e.target.value)}><option value="">Versión activa</option>{catalogs?.versions?.map((v:any)=><option key={v.id} value={v.id}>{v.fiscalYear}.{v.versionNumber} · {v.status}</option>)}</select>
      <select style={selectStyle} value={draft.companyId||''} onChange={e=>update('companyId',e.target.value)}><option value="">Todas las empresas</option>{catalogs?.companies?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select style={selectStyle} value={draft.countryId||''} onChange={e=>update('countryId',e.target.value)}><option value="">Todos los países</option>{catalogs?.countries?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
      <select style={selectStyle} value={draft.businessUnit||''} onChange={e=>update('businessUnit',e.target.value)}><option value="">Todas las unidades</option>{[...new Set<string>(catalogs?.dimensions?.map((x:any)=>x.businessUnit)||[])].map(x=><option key={x}>{x}</option>)}</select>
      <select style={selectStyle} value={draft.area||''} onChange={e=>update('area',e.target.value)}><option value="">Todas las áreas</option>{[...new Set<string>(catalogs?.dimensions?.map((x:any)=>x.area)||[])].map(x=><option key={x}>{x}</option>)}</select>
      <select style={selectStyle} value={draft.account||''} onChange={e=>update('account',e.target.value)}><option value="">Todas las cuentas</option>{[...new Map((catalogs?.dimensions||[]).map((x:any)=>[x.accountCode,x])).values()].map((x:any)=><option key={x.accountCode} value={x.accountCode}>{x.accountCode}</option>)}</select>
      <select style={selectStyle} value={draft.month||''} onChange={e=>update('month',e.target.value?Number(e.target.value):undefined)}><option value="">Todos los meses</option>{monthNames.map((name,index)=><option key={name} value={index+1}>{name}</option>)}</select>
      <Flex gap="2"><Button flex="1" colorPalette="blue" onClick={apply}>Aplicar</Button><Button variant="outline" onClick={()=>{setDraft(initial);setFilters(initial);void load(initial);}}>Limpiar</Button></Flex>
    </Grid></Box>
    {error&&<Box bg="red.50" color="red.700" p="4" rounded="xl">{error}</Box>}{loading&&<Flex justify="center" py="10"><Spinner size="xl"/></Flex>}
    {!loading&&result&&<><Grid templateColumns={{base:'1fr 1fr',xl:'repeat(4,1fr)'}} gap="3"><Metric label="Presupuesto anual (página)" value={money(totals.annual)}/><Metric label="Comprometido" value={money(totals.committed)}/><Metric label="Ejecutado" value={money(totals.executed)}/><Metric label="Disponible" value={money(totals.available)}/></Grid>
      <Box bg="white" borderWidth="1px" rounded="2xl" overflowX="auto"><Table.Root size="sm"><Table.Header><Table.Row>{[['businessUnit','Unidad'],['area','Área'],['accountCode','Cuenta'],['annualAmount','Anual']].map(([key,label])=><Table.ColumnHeader key={key}><Button size="xs" variant="ghost" onClick={()=>sort(key)}>{label}{filters.sortBy===key&&(filters.sortOrder==='asc'?<ChevronUp size={13}/>:<ChevronDown size={13}/>)}</Button></Table.ColumnHeader>)}<Table.ColumnHeader>Mes</Table.ColumnHeader><Table.ColumnHeader>Mensual</Table.ColumnHeader><Table.ColumnHeader>Comprometido</Table.ColumnHeader><Table.ColumnHeader>Ejecutado</Table.ColumnHeader><Table.ColumnHeader>Disponible</Table.ColumnHeader><Table.ColumnHeader/></Table.Row></Table.Header><Table.Body>{result.data.map((row:any)=><Table.Row key={row.id}><Table.Cell>{row.businessUnit}</Table.Cell><Table.Cell>{row.area}</Table.Cell><Table.Cell><Text fontWeight="semibold">{row.accountCode}</Text><Text fontSize="xs" color="gray.500">{row.accountDescription}</Text></Table.Cell><Table.Cell>{money(row.annualBudget,row.currency)}</Table.Cell><Table.Cell>{row.month?monthNames[row.month-1]:'Todos'}</Table.Cell><Table.Cell>{row.month?money(row.monthlyBudget,row.currency):'—'}</Table.Cell><Table.Cell>{money(row.month?row.monthlyCommitted:row.committed,row.currency)}</Table.Cell><Table.Cell>{money(row.month?row.monthlyExecuted:row.executed,row.currency)}</Table.Cell><Table.Cell>{money(row.month?row.monthlyAvailable:row.available,row.currency)}</Table.Cell><Table.Cell><Button size="xs" variant="outline" onClick={()=>open(row.id)}>Detalle</Button></Table.Cell></Table.Row>)}</Table.Body></Table.Root><Flex justify="space-between" p="4"><Text fontSize="sm">{result.meta.total} partidas · Página {result.meta.page} de {result.meta.totalPages}</Text><Flex gap="2"><Button size="sm" disabled={result.meta.page<=1} onClick={()=>page(result.meta.page-1)}>Anterior</Button><Button size="sm" disabled={result.meta.page>=result.meta.totalPages} onClick={()=>page(result.meta.page+1)}>Siguiente</Button></Flex></Flex></Box></>}
    {detail&&<BudgetDetail value={detail} close={()=>setDetail(undefined)}/>}</VStack>;
}
function Metric({label,value}:{label:string;value:string}){return <Box bg="white" borderWidth="1px" rounded="xl" p="4"><Text fontSize="xs" color="gray.500">{label}</Text><Text fontSize="xl" fontWeight="bold">{value}</Text></Box>}
function BudgetDetail({value,close}:{value:any;close:()=>void}){return <Box bg="white" borderWidth="1px" rounded="2xl" p="5"><Flex justify="space-between"><Box><Heading size="md">Detalle de partida {value.accountCode}</Heading><Text color="gray.500">Versión {value.version.fiscalYear}.{value.version.versionNumber} · {value.businessUnit} · {value.area}</Text></Box><Button variant="ghost" onClick={close}><X size={18}/></Button></Flex><Grid templateColumns={{base:'1fr 1fr',lg:'repeat(4,1fr)'}} gap="3" my="4"><Metric label="Presupuesto anual" value={money(value.annualBudget,value.currency)}/><Metric label="Comprometido" value={money(value.committed,value.currency)}/><Metric label="Ejecutado" value={money(value.executed,value.currency)}/><Metric label="Disponible" value={money(value.available,value.currency)}/></Grid><Heading size="sm" mb="2">Distribución mensual</Heading><Box overflowX="auto"><Table.Root size="sm"><Table.Header><Table.Row><Table.ColumnHeader>Mes</Table.ColumnHeader><Table.ColumnHeader>Presupuesto</Table.ColumnHeader><Table.ColumnHeader>Comprometido</Table.ColumnHeader><Table.ColumnHeader>Ejecutado</Table.ColumnHeader><Table.ColumnHeader>Disponible</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{value.periods.map((p:any)=><Table.Row key={p.id}><Table.Cell>{monthNames[p.month-1]}</Table.Cell><Table.Cell>{money(p.approved,value.currency)}</Table.Cell><Table.Cell>{money(p.committed,value.currency)}</Table.Cell><Table.Cell>{money(p.executed,value.currency)}</Table.Cell><Table.Cell>{money(p.available,value.currency)}</Table.Cell></Table.Row>)}</Table.Body></Table.Root></Box><Heading size="sm" mt="5" mb="2">Solicitudes relacionadas</Heading><Box overflowX="auto"><Table.Root size="sm"><Table.Header><Table.Row><Table.ColumnHeader>Número</Table.ColumnHeader><Table.ColumnHeader>Fecha</Table.ColumnHeader><Table.ColumnHeader>Solicitante</Table.ColumnHeader><Table.ColumnHeader>Monto</Table.ColumnHeader><Table.ColumnHeader>Comprometido</Table.ColumnHeader><Table.ColumnHeader>Estado</Table.ColumnHeader></Table.Row></Table.Header><Table.Body>{value.relatedRequests.map((r:any)=><Table.Row key={r.reservationId}><Table.Cell>{r.number}</Table.Cell><Table.Cell>{new Date(r.date).toLocaleDateString('es-GT')}</Table.Cell><Table.Cell>{r.requester}</Table.Cell><Table.Cell>{money(r.requestedAmount,r.currency)}</Table.Cell><Table.Cell>{money(r.committedAmount,r.currency)}</Table.Cell><Table.Cell><Badge>{r.requestStatus} / {r.reservationStatus}</Badge></Table.Cell></Table.Row>)}</Table.Body></Table.Root>{!value.relatedRequests.length&&<Text color="gray.500" py="4">No existen solicitudes relacionadas.</Text>}</Box></Box>}
