import { useEffect, useState } from 'react';
import { Avatar, Badge, Box, Button, Flex, HStack, IconButton, Menu, Portal, Text, VStack } from '@chakra-ui/react';
import { Bell, CheckCheck, ChevronDown, LogOut, ShieldCheck, User } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { notificationsService, type WorkflowNotification } from '../services/notifications.service';
import { exchangeRatesService, type ExchangeRate } from '../services/exchangeRates.service';
import { breadcrumbLabels, readUser } from '../navigation/navigation';

export function Header(){const location=useLocation(),navigate=useNavigate(),user=readUser(),title=breadcrumbLabels(location.pathname).at(-1)||'Sistema OPEX';const logout=()=>{localStorage.removeItem('access_token');localStorage.removeItem('user');navigate('/login',{replace:true})};return <Flex as="header" h="72px" bg="white" borderBottomWidth="1px" px={{base:'16',md:'6'}} align="center" justify="space-between" position="sticky" top="0" zIndex="20"><Box minW="0"><Text fontSize="xs" color="gray.500" display={{base:'none',sm:'block'}}>Sistema de Gestión y Control Presupuestario</Text><Text fontWeight="bold" truncate>{title}</Text></Box><HStack><CurrentRates/><NotificationMenu/><Menu.Root><Menu.Trigger asChild><Button variant="ghost" aria-label="Menú de usuario"><Avatar.Root size="sm"><Avatar.Fallback name={user.name||'Usuario'}/></Avatar.Root><VStack gap="0" align="start" display={{base:'none',md:'flex'}}><Text fontSize="sm">{user.name}</Text><Text fontSize="xs" color="gray.500">{user.role}</Text></VStack><ChevronDown size={15}/></Button></Menu.Trigger><Portal><Menu.Positioner><Menu.Content><Menu.Item value="profile" onClick={()=>navigate('/mi-perfil/seguridad')}><User size={16}/>Mi perfil</Menu.Item><Menu.Item value="security" onClick={()=>navigate('/mi-perfil/seguridad')}><ShieldCheck size={16}/>Seguridad</Menu.Item><Menu.Separator/><Menu.Item value="logout" color="red.600" onClick={logout}><LogOut size={16}/>Cerrar sesión</Menu.Item></Menu.Content></Menu.Positioner></Portal></Menu.Root></HStack></Flex>}
function CurrentRates(){const[rates,setRates]=useState<ExchangeRate[]>([]);useEffect(()=>{exchangeRatesService.current().then(setRates).catch(()=>setRates([]))},[]);if(!rates.length)return null;const first=rates[0];return <Box display={{base:'none',lg:'block'}} px="3" py="1" bg="blue.50" rounded="lg"><Text fontSize="xs">{first.fromCurrency.code} → {first.toCurrency.code} = {Number(first.rate).toLocaleString('es-GT')}</Text></Box>}
function NotificationMenu(){const navigate=useNavigate(),[items,setItems]=useState<WorkflowNotification[]>([]),[unread,setUnread]=useState(0);const load=async()=>{try{const[i,c]=await Promise.all([notificationsService.latest(),notificationsService.unreadCount()]);setItems(i);setUnread(c)}catch{setItems([]);setUnread(0)}};useEffect(()=>{void load();const timer=setInterval(load,60000);return()=>clearInterval(timer)},[]);return <Menu.Root onOpenChange={d=>{if(d.open)void load()}}><Menu.Trigger asChild><Box position="relative"><IconButton aria-label="Notificaciones" variant="outline"><Bell size={18}/></IconButton>{unread>0&&<Badge position="absolute" top="-2" right="-2" colorPalette="red">{unread>99?'99+':unread}</Badge>}</Box></Menu.Trigger><Portal><Menu.Positioner><Menu.Content minW="330px"><Flex p="3" justify="space-between"><Text fontWeight="bold">Notificaciones</Text><Button size="xs" variant="ghost" onClick={async()=>{await notificationsService.markAllRead();await load()}}><CheckCheck size={14}/>Marcar todas</Button></Flex>{items.map(item=><Menu.Item key={item.id} value={item.id} onClick={()=>navigate(`/notificaciones/${item.id}`)}><Box><Text fontSize="sm" fontWeight="semibold">{item.title}</Text><Text fontSize="xs" color="gray.500">{item.description}</Text></Box></Menu.Item>)}</Menu.Content></Menu.Positioner></Portal></Menu.Root>}
