import { Badge, Box, Button, Flex, Image, Text, VStack } from '@chakra-ui/react';
import { ChevronDown, ChevronRight, PanelLeftClose, PanelLeftOpen, X } from 'lucide-react';
import { NavLink, useLocation } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { visibleNavigation, type NavigationGroup, type NavigationItem } from '../navigation/navigation';

export function Sidebar({collapsed,onToggle,mobileOpen,onMobileClose,counters={}}:{collapsed:boolean;onToggle:()=>void;mobileOpen:boolean;onMobileClose:()=>void;counters?:Record<string,number>}){
 const location=useLocation(),items=visibleNavigation();
 const [open,setOpen]=useState<Record<string,boolean>>(()=>{try{return JSON.parse(localStorage.getItem('sidebarGroups')||'{}')}catch{return {}}});
 useEffect(()=>{localStorage.setItem('sidebarGroups',JSON.stringify(open))},[open]);
 useEffect(()=>{onMobileClose()},[location.pathname]);
 useEffect(()=>{if(!mobileOpen)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onMobileClose()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[mobileOpen]);
 const width=collapsed?'76px':'280px';
 return <><Box position="fixed" inset="0" bg="blackAlpha.500" zIndex="39" display={{base:mobileOpen?'block':'none',lg:'none'}} onClick={onMobileClose}/><Box as="nav" aria-label="Navegación principal" position="fixed" left="0" top="0" h="100vh" w={{base:'280px',lg:width}} transform={{base:mobileOpen?'translateX(0)':'translateX(-100%)',lg:'none'}} transition="width .2s, transform .2s" bg="white" borderRightWidth="1px" zIndex="40" overflowY="auto" p="3"><Flex align="center" justify="space-between" minH="60px"><Image src="/images/logo-servicios-compartidos.jpg" alt="Servicios Compartidos" maxW={collapsed?'44px':'170px'}/><Button display={{base:'inline-flex',lg:'none'}} size="sm" variant="ghost" aria-label="Cerrar menú" onClick={onMobileClose}><X/></Button></Flex><Button display={{base:'none',lg:'inline-flex'}} w="full" size="sm" variant="ghost" aria-label={collapsed?'Expandir menú':'Colapsar menú'} title={collapsed?'Expandir menú':'Colapsar menú'} onClick={onToggle}>{collapsed?<PanelLeftOpen/>:<><PanelLeftClose/><Text>Colapsar</Text></>}</Button><VStack align="stretch" gap="1" mt="3">{items.map((item:any)=>'children'in item?<Group key={item.label} item={item} collapsed={collapsed} opened={open[item.label]??item.children.some((c:any)=>location.pathname.startsWith(c.path))} toggle={()=>setOpen(v=>({...v,[item.label]:!(v[item.label]??true)}))} counters={counters}/>:<LinkItem key={item.path} item={item} collapsed={collapsed} counters={counters}/>)}</VStack></Box></>;
}
function Group({item,collapsed,opened,toggle,counters}:{item:NavigationGroup;collapsed:boolean;opened:boolean;toggle:()=>void;counters:Record<string,number>}){const Icon=item.icon;return <Box><Button w="full" variant="ghost" justifyContent={collapsed?'center':'space-between'} aria-expanded={opened} aria-label={item.label} title={collapsed?item.label:undefined} onClick={toggle}><Flex gap="3"><Icon size={19}/>{!collapsed&&<Text>{item.label}</Text>}</Flex>{!collapsed&&(opened?<ChevronDown size={16}/>:<ChevronRight size={16}/>)}</Button>{!collapsed&&opened&&<VStack align="stretch" pl="3" gap="1">{item.children.map(child=><LinkItem key={child.path} item={child} collapsed={false} counters={counters}/>)}</VStack>}{collapsed&&opened&&<Box position="relative">{item.children.map(child=><LinkItem key={child.path} item={child} collapsed counters={counters}/>)}</Box>}</Box>}
function LinkItem({item,collapsed,counters}:{item:NavigationItem;collapsed:boolean;counters:Record<string,number>}){const Icon=item.icon,count=item.counter?counters[item.counter]:0;return <NavLink to={item.path} title={collapsed?item.label:undefined} aria-label={item.label}>{({isActive})=><Flex align="center" justify={collapsed?'center':'space-between'} gap="2" px="3" py="2.5" rounded="lg" bg={isActive?'blue.50':'transparent'} color={isActive?'blue.700':'gray.700'} fontWeight={isActive?'bold':'medium'} _hover={{bg:'gray.100'}} _focusVisible={{outline:'2px solid',outlineColor:'blue.500'}}><Flex gap="3" align="center"><Icon size={18}/>{!collapsed&&<Text fontSize="sm">{item.label}</Text>}</Flex>{!collapsed&&count>0&&<Badge colorPalette="red">{count>99?'99+':count}</Badge>}</Flex>}</NavLink>}
