import { Badge, Box, Button, Flex, Grid, Heading, Input, Stack, Text } from "@chakra-ui/react";
import { useEffect, useState } from "react";
import { api } from "../../shared/services/api";

type MetricGroup = { label: string; value: number };
type Metrics = { status: Record<string, number>; total: number; averageOcrMs: number; averageReviewMs: number; averageConfidence: number; corrections: number; averageDetectedFields: number; averageOmittedFields: number; byCountry: MetricGroup[]; byType: MetricGroup[]; byCompany: MetricGroup[] };

function Bars({ title, values }: { title: string; values: MetricGroup[] }) { const max = Math.max(1, ...values.map(item => item.value)); return <Box borderWidth="1px" borderRadius="xl" p="5"><Heading size="sm" mb="4">{title}</Heading><Stack gap="3">{values.map(item => <Box key={item.label}><Flex justify="space-between"><Text fontSize="sm">{item.label}</Text><Text fontWeight="bold">{item.value}</Text></Flex><Box bg="gray.100" h="8px" borderRadius="full"><Box bg="blue.500" h="8px" borderRadius="full" width={`${item.value / max * 100}%`}/></Box></Box>)}{!values.length && <Text color="gray.500">Sin datos para el periodo.</Text>}</Stack></Box>; }

export function OcrAnalyticsPage() {
  const [metrics, setMetrics] = useState<Metrics | null>(null);
  useEffect(() => { api.get("/ocr/analytics/metrics").then(response => setMetrics(response.data)); }, []);
  if (!metrics) return <Text p="8">Cargando metricas OCR...</Text>;
  const cards = [
    ["Documentos cargados", metrics.total], ["Procesados", metrics.status.PROCESADO || metrics.status.PENDIENTE_REVISION || 0], ["Pendientes", metrics.status.PENDIENTE_REVISION || 0], ["Confirmados", (metrics.status.CONFIRMADO || 0) + (metrics.status.ASOCIADO_SOLICITUD || 0)], ["Error OCR", metrics.status.ERROR_OCR || 0], ["Tiempo promedio OCR", `${(metrics.averageOcrMs / 1000).toFixed(2)} s`], ["Tiempo promedio revision", `${(metrics.averageReviewMs / 60000).toFixed(2)} min`], ["Confianza promedio", `${metrics.averageConfidence.toFixed(2)} %`], ["Correcciones", metrics.corrections], ["Campos detectados promedio", metrics.averageDetectedFields.toFixed(2)], ["Campos omitidos promedio", metrics.averageOmittedFields.toFixed(2)],
  ];
  return <Box p={{ base: "4", md: "8" }}><Heading mb="2">Dashboard OCR</Heading><Text color="gray.600" mb="6">Indicadores calculados desde documentos y auditorias reales.</Text><Grid templateColumns={{ base: "1fr 1fr", lg: "repeat(4, 1fr)" }} gap="4">{cards.map(([label, value]) => <Box key={String(label)} borderWidth="1px" borderRadius="xl" p="4" bg="white"><Text color="gray.500" fontSize="sm">{label}</Text><Text fontSize="2xl" fontWeight="bold">{value}</Text></Box>)}</Grid><Grid templateColumns={{ base: "1fr", lg: "repeat(3, 1fr)" }} gap="5" mt="6"><Bars title="Documentos por pais" values={metrics.byCountry}/><Bars title="Documentos por tipo" values={metrics.byType}/><Bars title="Documentos por empresa" values={metrics.byCompany}/></Grid></Box>;
}

export function OcrReportPage() {
  const [rows, setRows] = useState<any[]>([]); const [filters, setFilters] = useState({ dateFrom: "", dateTo: "", status: "", country: "", documentType: "" });
  const load = async () => setRows((await api.get("/reports/ocr", { params: filters })).data.data);
  useEffect(() => { void load(); }, []);
  const exportFile = async (format: "excel" | "pdf") => { const response = await api.get(`/reports/ocr/export/${format}`, { params: filters, responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = `reporte-ocr.${format === "excel" ? "xlsx" : "pdf"}`; link.click(); URL.revokeObjectURL(url); };
  return <Box p={{ base: "4", md: "8" }}><Heading mb="5">Reportes OCR</Heading><Grid templateColumns={{ base: "1fr", md: "repeat(5, 1fr)" }} gap="3"><Input type="date" value={filters.dateFrom} onChange={e => setFilters({...filters,dateFrom:e.target.value})}/><Input type="date" value={filters.dateTo} onChange={e => setFilters({...filters,dateTo:e.target.value})}/><Input placeholder="Estado" value={filters.status} onChange={e => setFilters({...filters,status:e.target.value})}/><Input placeholder="Pais" value={filters.country} onChange={e => setFilters({...filters,country:e.target.value})}/><Input placeholder="Tipo documental" value={filters.documentType} onChange={e => setFilters({...filters,documentType:e.target.value})}/></Grid><Flex gap="3" my="4"><Button onClick={() => void load()}>Aplicar filtros</Button><Button variant="outline" onClick={() => void exportFile("excel")}>Exportar Excel</Button><Button variant="outline" onClick={() => void exportFile("pdf")}>Exportar PDF</Button></Flex><Box overflowX="auto"><Box as="table" width="100%"><Box as="thead"><Box as="tr">{["Documento","Empresa","Fecha","Total","Estado","Confianza","Usuario","Tiempo OCR","Tiempo revision","Correcciones"].map(value => <Box as="th" p="3" textAlign="left" key={value}>{value}</Box>)}</Box></Box><Box as="tbody">{rows.map(row => <Box as="tr" key={row.id}>{[row.document,row.company,new Date(row.date).toLocaleDateString(),row.total,row.status,`${Number(row.averageConfidence).toFixed(2)} %`,row.user,`${row.ocrTimeMs} ms`,row.reviewTimeMs == null ? "Pendiente" : `${Math.round(row.reviewTimeMs / 60000)} min`,row.corrections].map((value,index) => <Box as="td" borderTopWidth="1px" p="3" key={index}>{index === 4 ? <Badge>{value}</Badge> : value}</Box>)}</Box>)}</Box></Box></Box></Box>;
}
